name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./docker/
      run: docker build . --file Dockerfile --tag markl4yg/informaticup:latest
