name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./docker/
      run: docker build . --file Dockerfile --tag markl4yg/informaticup-2020:latest
    - name: Publish the Docker image
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: markl4yg/informaticup-2020
        dockerimage: docker/Dockerimage 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
